language: node_js
node_js:
- '4.1'
env:
  global:
  - NON_SECRET_KEY=blablablabla
  #SECRET_KEY=secretvalue
  - secure: mXovwXJyY8y6vVr8TrLwdQC7YuLLRJ7jReXNKcUw5x2f/8mw1cp+NTOi9cRzbXyotoNLX6uYypMbb3bV6ImO6Wwk/QnLD++btGQ0hs516B3+RJLNiwL7PoGGo5C82ItXuRDp67hlSV4xPnaf0vWvArfeqfAUV9tRX+tPoYJK7hf8J603osQ2kPKWPkrCnSDRs9e0yUFAlK26kMk7H+s5SSO+pWdquI0utwHVWiEhUsrE1AfXxzyxIlfURY1GQuAwwe3n8bHnlCkts/frhs82kWtX+kU3lRwmuwiwEN19ayvA4rdZAZtcFgfp3heUNnSEZ2Jd3NYh29cFyo9vhwvgaWKOgHK3Qbh5HjiQ4HvDOjwPP53AEaVWmV6ZJcEY2WhvO9+/Gv8+YZWZi4i2w2U0c1o4ssIgxTaq6JJXrKh5n8QGabfSoxoFdECcjfRAMQT6eg2NOYtumm77zfs6x43UN57m5nFsPQxCjBWCC4z7P/QAVWKqDf4WeqHwUUyx4jVRGWO4EFfO2ugftC4lPtI1019hPDuWQIzCLtCXaf6C1cYMFupZgM405EMqeBJq++RVBkWt1CTKCCSQUZKl53oZGx/BJjQc7bjLis60NBzt0S2LaYkUxBpT1t0oe3CInj+AaRpKnRdbc3jIzP+cekMP75W/W8TR+RidydBvBCHIEh0=

